### ISSUE TITLE
[BUG] Tidak ada titik pemisah harga di bagian add produk

### ISSUE THREAD

**Issue by GNC06** [lokuswp/lwcommerce#74]
saya mencoba input pruduk baru menurut saya lebih baik ada tanda (.) titik dibagian harga agar pengguna lebih enak dalam menbacanya.

**Comment by lasida** [comment]
oke, terimakasih mas @GNC06  buat masukannya :+1:  segera kita perbaiki

**Comment by lasida** [comment]
done
