### ISSUE TITLE
[REQUEST] Fitur Export Data Pesanan ke CSV

### ISSUE THREAD

**Issue by lasida** [lokuswp/lwcommerce#76]
Mas @Chariselyasa123  request fitur export data pesanan ke csv dong, buat bikin konten tentang cara ngumpulin database pengguna pake LWCommerce

thankyou

**Comment by Chariselyasa123** [comment]
Done

**Comment by Chariselyasa123** [comment]
Done

**Comment by lasida** [comment]
![image](https://user-images.githubusercontent.com/8340974/173492133-d9715bb5-72f1-4b75-8f7f-40b22e2d18a0.png)

oke, sudah mantap, paling minta tambahin 1 kolom lagi mas @Chariselyasa123, payment_id, sama status itu ada 2
payment_status : ( paid, unpaid ) order_status : ( pending, processing, shipping, completed )

sama minta tolong 1 lagi, tambahin **gambar metode pembayaran** di bagian order

**Comment by lasida** [comment]
Fixed
