### ISSUE TITLE
List shorcode

### ISSUE THREAD

**Issue by yanz0806** [lokuswp/lwcommerce#91]
mohon untuk di tampilkan list shorcode untuk membuat template pesan notifikasi

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/116194477/197464613-c8bc655a-1e8c-439a-a635-2ecaec089af0.png">

**Comment by lasida** [comment]
baik mas, nanti kita tambahkan di update selanjutnya, tag yang bisa dipake same nggak, makasih masukannya

**Comment by lasida** [comment]
done mas, bisa cek di https://lokuswp.id/panduan/lwcommerce/pengaturan/notifikasi-whatsapp.html
